### ISSUE TITLE
~gpu ?

### ISSUE THREAD

**Issue by fwyzard** [cms-patatrack/cmssw#133]
@makortel , can you think of a way to get rid of the `(~gpu)` modifier in [Configuration/StandardSequences/python/RawToDigi_cff.py](https://github.com/cms-patatrack/cmssw/blob/CMSSW_10_2_X_Patatrack/Configuration/StandardSequences/python/RawToDigi_cff.py#L80) ?

**Comment by makortel** [comment]
To first order it is needed a it is.

Nevertheless, possible ways to remove it are
* add dummy `InputLabel` parameter to [SiPixelDigiHeterogeneousConverter](https://github.com/cms-patatrack/cmssw/blob/CMSSW_10_2_X_Patatrack/RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelDigiHeterogeneousConverter.cc)
* change the default `InputLabel` to `rawDataCollector`, but I have no idea what that would break https://github.com/cms-patatrack/cmssw/blob/12f20c13e1a3a5106b89085e881f4b734ee758c7/EventFilter/SiPixelRawToDigi/plugins/SiPixelRawToDigi.cc#L141

**Comment by makortel** [comment]
The latest version of #100 will remove the `(~gpu)`.

**Comment by fwyzard** [comment]
Fixed by #100.
