### ISSUE TITLE
caHitQuadrupletDefault ?

### ISSUE THREAD

**Issue by fwyzard** [cms-patatrack/cmssw#135]
@felicepantaleo I am trying to reconcile changes between CMSSW_10_2_X_Patatrack branch and CMSSW_10_2_X.

Do we actually need to [change the default label for the CA to `caHitQuadrupletDefault`](https://github.com/cms-patatrack/cmssw/blob/CMSSW_10_2_X_Patatrack/RecoPixelVertexing/PixelTriplets/interface/CAHitQuadrupletGenerator.h#L44) ?
Or, can we revert this change (and update [RecoPixelVertexing/PixelTriplets/python/caHitQuadrupletEDProducer_cfi.py](https://github.com/cms-patatrack/cmssw/blob/CMSSW_10_2_X_Patatrack/RecoPixelVertexing/PixelTriplets/python/caHitQuadrupletEDProducer_cfi.py) accordingly) ?

**Comment by makortel** [comment]
We need it, unless we change the way of propagating CA configuration parameters from initialStep to pixelTracks (e.g. by leaving `caHitQuadrupletEDProducer_cfi` to define the CPU-only producer, importing the GPU one in [`pixelTracks_cff`](https://github.com/cms-patatrack/cmssw/blob/CMSSW_10_2_X_Patatrack/RecoPixelVertexing/PixelTrackFitting/python/PixelTracks_cff.py), doing the `toReplaceWith` there and copying parameter values to the new one).
