### ISSUE TITLE
kernels don't overlap on multiple streams

### ISSUE THREAD

**Issue by felicepantaleo** [cms-patatrack/cmssw#183]
At the hackathon we noticed that using more CUDA streams was not beneficial on one GPU, and that kernel executions never overlap.

By replacing a kernel with a long for loop and we come to the same conclusion, although we know that there is room for other kernels to overlap. 
~~Maybe when we create a stream and still using  per-thread default stream option~~
![image](https://user-images.githubusercontent.com/6595715/46373273-dc174100-c68d-11e8-92f8-eceeb506f91e.png)

From a quick search this might be related to the stream callback:
https://devtalk.nvidia.com/default/topic/822942/why-does-cudastreamaddcallback-serialize-kernel-execution-and-break-concurrency-/

Although with the code they provide and I see overlap so it was probably fixed on nvidia side:
http://fpantale.web.cern.ch/fpantale/withcallback.nvvp

Maybe this is still related and we are in a very special case?
@makortel @rovere @fwyzard @VinInn

**Comment by felicepantaleo** [comment]
for lazy people:
![image](https://user-images.githubusercontent.com/6595715/46376300-f3f2c300-c695-11e8-9581-75d6d8317c3e.png)

**Comment by makortel** [comment]
> Maybe when we create a stream and still using per-thread default stream option

We use `cudaStreamDefault` flag for `cudaStreamCreateWithPriority()` 
https://github.com/cms-patatrack/cmssw/blob/58a5ecb2c5e34a114c2729de80e514625aad4b49/HeterogeneousCore/CUDACore/src/GPUCuda.cc#L55
We could of course test `cudaStreamNonBlocking` (or `cuda::stream::no_implicit_synchronization_with_default_stream` in the api wrappers term). But since we don't use stream 0 for anything, it shouldn't really matter, right (or have I misunderstood the docs)?

@felicepantaleo Could you provide the nvvp file corresponding the picture in the description?

**Comment by felicepantaleo** [comment]
> Maybe when we create a stream and still using per-thread default stream option

Sorry, this I wrote before I verified that the compiler option was not the culprit. 

The thread which performs the callback is always the same I suppose (a helper thread from a "CUDA" pool) and does not belong to the framework, right?

**Comment by rovere** [comment]
Here it the profile: [link](https://cernbox.cern.ch/index.php/s/7B382v9PTt7Xhum)

**Comment by fwyzard** [comment]
> The thread which performs the callback is always the same I suppose (a helper thread from a "CUDA" pool) and does not belong to the framework, right?

I do not know if it is always the same, or if CUDA keeps a thread pool. Anyway, no, it is not one of the threads used by the framework.

**Comment by felicepantaleo** [comment]
I was able to reproduce our behavior in a standalone application:

http://www.cern.ch/felice.pantaleo/withcallbackSleep.nvvp

I added a 100ms sleep in the callback function. After the first overlap, everything else is serialized.


![image](https://user-images.githubusercontent.com/6595715/46409503-1f1cf700-c716-11e8-9e5c-3847dfbcdf4b.png)



```
#include "cuda_runtime.h"
#include "device_launch_parameters.h"
#include <iostream>
#include <chrono>
#include <thread>
#define NUM_STREAM  32
#define ARRAY_SIZE  1000000

int f = 0;
__global__ void kernel_looping(float* point, unsigned int num)
{
    unsigned int idx = threadIdx.x + blockIdx.x * blockDim.x;

    for (size_t offset = idx; offset < num; offset += gridDim.x * blockDim.x)
    {
        point[offset] += 1;
    }
}

void CUDART_CB callback(cudaStream_t stream, cudaError_t status, void *arg)
{

   f++;
std::this_thread::sleep_for(std::chrono::milliseconds(100));

}

int main()
{
    float *dev_points[NUM_STREAM];
    float *host_points[NUM_STREAM];
    cudaStream_t streams[NUM_STREAM];

    for (size_t i = 0; i < NUM_STREAM; ++i)
    {
        cudaMalloc(dev_points + i, ARRAY_SIZE * sizeof(float));
        cudaMallocHost(host_points + i, ARRAY_SIZE * sizeof(float));
        cudaStreamCreateWithFlags(streams + i, cudaStreamNonBlocking);
        for (size_t j = 0; j < ARRAY_SIZE; ++j)
        {
            host_points[i][j] = static_cast<float>(i + j);
        }
    }

    for( int j = 0; j < 4; ++j)
    for (size_t i = 0; i < NUM_STREAM; ++i)
    {
        cudaMemcpyAsync(dev_points[i], host_points[i], 
                                       ARRAY_SIZE * sizeof(float), 
                                       cudaMemcpyHostToDevice, streams[i]);
        kernel_looping<<<1, 16, 0, streams[i]>>>(dev_points[i], ARRAY_SIZE);
        cudaMemcpyAsync(host_points[i], dev_points[i], 
                                       ARRAY_SIZE * sizeof(float), 
                                       cudaMemcpyDeviceToHost, streams[i]);

        cudaStreamAddCallback(streams[i], callback, NULL, 0);
    }

    cudaDeviceSynchronize();
    std::cout << f << std::endl;
    for (size_t i = 0; i < NUM_STREAM; ++i)
    {
        cudaFree(dev_points[i]);
        cudaFreeHost(host_points[i]);
        cudaStreamDestroy(streams[i]);
    }
}
```

**Comment by rovere** [comment]
you mean serialized at 100ms boundaries?

**Comment by felicepantaleo** [comment]
we have replaced the callback with a `cudaStreamSynchronize` and things don't change.
we also added the above kernel and yet there is small overlap:
http://www.cern.ch/vincenzo.innocente/prof.nvpp

**Comment by makortel** [comment]
One difference between the profile (1) in description and https://github.com/cms-patatrack/cmssw/issues/183#issuecomment-426563628 and the test (2) https://github.com/cms-patatrack/cmssw/issues/183#issuecomment-426613970 is that in (2), the "Runtime API" is full of "cudaStreamAddCallback_ptsz", while in (1) the "Runtime API" is mostly empty. I suspect as well (https://github.com/cms-patatrack/cmssw/issues/183#issuecomment-426666865) that the reason for missing the overlaps is something else than the callbacks.

I'll play around with the test program (thanks @felicepantaleo). Regarding the original problem in the description, could someone provide an exact recipe to reproduce?

**Comment by felicepantaleo** [comment]
ciao Matti, 
what we did with Vincenzo is just to write this in our clusterizer :
```
__global__ void kernel_looping(float* point, unsigned int num)
{
    unsigned int idx = threadIdx.x + blockIdx.x * blockDim.x;

    for (size_t offset = idx; offset < num; offset += gridDim.x * blockDim.x)
    {
        point[offset] += 1;
    }
}

```

And then launch it on a preallocated data member `dev_points` without running copies.
Then adjust the length of the loop (with 1M elements it takes ~800ms).
Sorry, I cannot give you a branch as we did it with Vincenzo's account.

**Comment by makortel** [comment]
@felicepantaleo Thanks. Ok, so otherwise it is just the `CMSSW_10_2_X_Patatrack` HEAD, (or close enough), right?

**Comment by felicepantaleo** [comment]
@makortel yes

**Comment by makortel** [comment]
Thanks, I managed to reproduce.

**Comment by makortel** [comment]
I measured the time spent in the CMSSW callback (with std::chrono::high_resolution_clock::now()) to be on the average ~4.5 microseconds (with one ~100 us outlier) (100 TTbar+PU events).

**Comment by makortel** [comment]
The `StallMonitor` claims that from FW point of view  the system is given the async portions in parallel (i.e. with 2 EDM streams it shows that there are nearly always two modules in the "between `acquire()` and `produce()`" phase). The `nvvp` supports that showing that the two `acquire()`s are run right after the other, i.e. the second long-running kernel is given to CUDA way before the first kernel finishes.

**Comment by VinInn** [comment]
maybe is cudaMemsetAsync() that is designed to full occupancy?

**Comment by fwyzard** [comment]
> Then I noticed that many of the kernels launched in raw2cluster have "Theoretical occupancy" of 100 % (as reported by nvvp). Could those prevent the parallel execution of long-running (lightweight) kernels?

Yes.

However (as Felice explained to me) it should not prevent them from running in parallel to a long-running lightweight kernel, if they are submitted after it.

**Comment by makortel** [comment]
> > Then I noticed that many of the kernels launched in raw2cluster have "Theoretical occupancy" of 100 % (as reported by nvvp). Could those prevent the parallel execution of long-running (lightweight) kernels?
> 
> 
> Yes.
> 
> However (as Felice explained to me) it should not prevent them from running in parallel to a long-running lightweight kernel, if they are submitted after it.

In my test cases the two `acquire()`s are run sequentially, i.e. the chain "long-running lightweight kernel" + "short heavyweight kernels" are first fully submitted to one CUDA stream, and some time after that, fully to other CUDA stream.

On the other hand, I added a "heavy kernel" to the standalone test as well, and there it did not prevent a "lightweight" kernel from another CUDA stream being launched in parallel. So something else must be going on.

**Comment by makortel** [comment]
Ok, I encountered something pretty weird. I commented out everything from raw2cluster after the call to `gpuCalibPixel::calibDigis()` kernel. Eventually it calls `SiPixelGainForHLTonGPU::getPedAndGain()`. If I break out of the function (by returning `(0,1)`) just before the first `assert`
https://github.com/cms-patatrack/cmssw/blob/4d789ebde5a947df5eaea12781f1c0e8f530ba2d/CondFormats/SiPixelObjects/interface/SiPixelGainForHLTonGPU.h#L38-L42
I get the "long running" kernels (that are launched first) to run in parallel, and if I break out of the function just after the first `assert, the "long running" kernel of the second stream starts only after the `calibDigis()` kernel has finished.

**Comment by VinInn** [comment]
breaking before the assert will make the compiler optimize out all what comes first
the assert force offset to be computed
we can try to force to load everything in constant cache using __ldg (for range as well)

**Comment by makortel** [comment]
I can reproduce `assert` being the cause with this test program (minimal modifications to https://github.com/cms-patatrack/cmssw/issues/183#issuecomment-426613970)
```cpp
#include "cuda_runtime.h"
#include "device_launch_parameters.h"
#include <iostream>
#include <cassert>
#include <chrono>
#include <thread>
#define NUM_STREAM  32
#define ARRAY_SIZE  1000000

int f = 0;
__global__ void kernel_looping(float* point, unsigned int num)
{
    unsigned int idx = threadIdx.x + blockIdx.x * blockDim.x;

    for (size_t offset = idx; offset < num; offset += gridDim.x * blockDim.x)
    {
        point[offset] += 1;
    }
}

__global__ void kernel_assert(float* point, unsigned int num)
{
    unsigned int idx = threadIdx.x + blockIdx.x * blockDim.x;
    if(idx >= num)
        return;

    point[idx] += 1;
    assert(point[idx] > 0);
}

void CUDART_CB callback(cudaStream_t stream, cudaError_t status, void *arg)
{

   f++;
std::this_thread::sleep_for(std::chrono::milliseconds(100));

}

int main()
{
    float *dev_points[NUM_STREAM];
    float *host_points[NUM_STREAM];
    cudaStream_t streams[NUM_STREAM];

    for (size_t i = 0; i < NUM_STREAM; ++i)
    {
        cudaMalloc(dev_points + i, ARRAY_SIZE * sizeof(float));
        cudaMallocHost(host_points + i, ARRAY_SIZE * sizeof(float));
        cudaStreamCreateWithFlags(streams + i, cudaStreamNonBlocking);
        for (size_t j = 0; j < ARRAY_SIZE; ++j)
        {
            host_points[i][j] = static_cast<float>(i + j);
        }
    }

    for( int j = 0; j < 4; ++j)
    for (size_t i = 0; i < NUM_STREAM; ++i)
    {
        cudaMemcpyAsync(dev_points[i], host_points[i], 
                                       ARRAY_SIZE * sizeof(float), 
                                       cudaMemcpyHostToDevice, streams[i]);
        kernel_looping<<<1, 16, 0, streams[i]>>>(dev_points[i], ARRAY_SIZE);
        kernel_assert<<<200, 512, 0, streams[i]>>>(dev_points[i], ARRAY_SIZE);
        cudaMemcpyAsync(host_points[i], dev_points[i], 
                                       ARRAY_SIZE * sizeof(float), 
                                       cudaMemcpyDeviceToHost, streams[i]);

        cudaStreamAddCallback(streams[i], callback, NULL, 0);
    }

    cudaDeviceSynchronize();
    std::cout << f << std::endl;
    for (size_t i = 0; i < NUM_STREAM; ++i)
    {
        cudaFree(dev_points[i]);
        cudaFreeHost(host_points[i]);
        cudaStreamDestroy(streams[i]);
    }
}

```

**Comment by makortel** [comment]
@VinInn It looks to me that the cause could be the `assert` itself. The C Programming Guide says only

> Assertions are for debugging purposes. They can affect performance and it is therefore recommended to disable them in production code.

https://docs.nvidia.com/cuda/cuda-c-programming-guide/#assertion

**Comment by makortel** [comment]
> feel free to remove the assert and try again...

The programming guide says further
> They can be disabled at compile time by defining the NDEBUG preprocessor macro before including assert.

so I recompiled raw2cluster code with `NDEBUG` macro and now the long-running kernels run in parallel.

So should we add `-DNDEBUG` to `CUDA_CXXFLAGS`?

**Comment by makortel** [comment]
Thanks @fwyzard, I wasn't particularly fond of global `-DNDEBUG` either.

> That said, and not having had a chance to look at the code yet: do we run
> into this issue because the assert is checking some (expensive) conditions
> that are not used by the rest of the code ?

To me it looks that it is already the existence of the `assert` (as long as the condition can not be checked compile time) that triggers the behaviour. 

To give further evidence, I took my test program https://github.com/cms-patatrack/cmssw/issues/183#issuecomment-427432769 (and commented out the callback to not make the "with-assert" case profile look strange)

Here is the profile with the `assert` in the `kernel_assert`
https://mkortela.web.cern.ch/mkortela/patatrack/test2_nocallback_assert.nvvp
and it looks like this
![image](https://user-images.githubusercontent.com/33993/46559055-bcae2d00-c8b4-11e8-9f5d-cd7312c17b3b.png)

Commenting out the `assert` (and nothing else) gives
https://mkortela.web.cern.ch/mkortela/patatrack/test2_nocallback_noassert.nvvp
![image](https://user-images.githubusercontent.com/33993/46559113-e404fa00-c8b4-11e8-9e1f-9136b2ad9a0f.png)

**Comment by fwyzard** [comment]
I see... thanks for the check !

**Comment by fwyzard** [comment]
Here's a snapshot of the profiler with the asserts (from the current HEAD), running 1 job with 4 streams on a V100:
![image](https://user-images.githubusercontent.com/4069793/46565510-56ef8e80-c910-11e8-9127-2f2a185e4b5c.png)

And here is a snapshot of the profile os the same job, running without the asserts (#186):
![image](https://user-images.githubusercontent.com/4069793/46565529-7ab2d480-c910-11e8-8b48-ab3f74412b3a.png)

**Comment by makortel** [comment]
Nice!

**Comment by felicepantaleo** [comment]
![image](https://user-images.githubusercontent.com/6595715/46569267-c4241380-c952-11e8-90e7-d86c6cd8ff4f.png)
