### ISSUE TITLE
Implement/Translate CPU version of the GPU-only algorithms 

### ISSUE THREAD

**Issue by felicepantaleo** [cms-patatrack/cmssw#221]

**Comment by fwyzard** [comment]
I would consider any work that provides only the GPU version of an algorithm as utterly incomplete, unusable, and not worth the effort of integration in the upstream CMSSW.

**Comment by fwyzard** [comment]
@rovere @felicepantaleo @VinInn as of CMSSW 10.6.0-Patatrack, what is the status of what can and cannot be converted to legacy format ?

**Comment by VinInn** [comment]
Everything CAN be (and by default IS) converted in Legacy Format (infact DQM works out of the box for both MC and data)

**Comment by fwyzard** [comment]
Thanks !
