### ISSUE TITLE
Port producers to SwitchProducer  

### ISSUE THREAD

**Issue by felicepantaleo** [cms-patatrack/cmssw#229]

**Comment by makortel** [comment]
Here is the list of producers to be migrated
- [ ] `SiPixelRawToClusterHeterogeneous` (done in #100)
- [ ] `SiPixelRecHitHeterogeneous`
- [ ] `CAHitNtupletHeterogeneousEDProducer`
- [ ] `PixelTrackProducerFromCUDA`
- [ ] `PixelVertexHeterogeneousProducer`
- [ ] `ClusterTPAssociationHeterogeneous`

**Comment by makortel** [comment]
After the latest developments `ClusterTPAssociationHeterogeneous` is the only remaining `HeterogeneousEDProducer`.

@VinInn Do you have any plans to migrate it?
