### ISSUE TITLE
What does the `pixelNtupleFit` modifier do ?

### ISSUE THREAD

**Issue by fwyzard** [cms-patatrack/cmssw#352]
The `.51` workflows add the `pixelNtupleFit` modifier to the pixel tracking-only configuration.

However, according to a [recent validation](https://fwyzard.web.cern.ch/fwyzard/patatrack/pulls/0e43509f8a49342aa074633b81d38bc96dace0af/RelValTTbar_13-CMSSW_10_6_0-PU25ns_106X_upgrade2018_design_v3-v1/10824.51/index.html), it does not seem to do much ?

**Comment by VinInn** [comment]
"This modifier is for replacing the default pixel track "fitting" with eihter Riemann or BrokenLine fit"
replace obsoleted "riemannFit" modifier

**Comment by VinInn** [comment]
which fit is used is controlled by
process.pixelNtupletsFitter.useRiemannFit = True 
(or False for BrokenLine)
