### ISSUE TITLE
move validation to 2021 samples

### ISSUE THREAD

**Issue by fwyzard** [cms-patatrack/cmssw#459]
I am thinking of moving the validation of the Patatrack PRs from 2018 samples to 2021 samples
any other suggestions, 

@makortel @VinInn any objections or comments ?

**Comment by VinInn** [comment]
+1.

Ideal or realistic?

**Comment by fwyzard** [comment]
I see only `realistic` samples for 2021:
```
$ dasgoclient --query 'dataset dataset=/RelValTTbar*/CMSSW_11_1_0_pre6*2021*/GEN-SIM-DIGI-RAW'
/RelValTTbar_14TeV/CMSSW_11_1_0_pre6-111X_mcRun3_2021_realistic_v3-v1/GEN-SIM-DIGI-RAW
/RelValTTbar_14TeV/CMSSW_11_1_0_pre6-PU_111X_mcRun3_2021_realistic_v3-v1/GEN-SIM-DIGI-RAW
/RelValTTbar_14TeV/CMSSW_11_1_0_pre6-PU_111X_mcRun3_2021_realistic_v3_rsb-v1/GEN-SIM-DIGI-RAW
```

**Comment by VinInn** [comment]
ok, needs to understand what does really mean... will have a look at DQM (smile-plot)

**Comment by makortel** [comment]
Makes sense to me.

**Comment by fwyzard** [comment]
OK, [this](https://github.com/cms-patatrack/cmssw/issues/460#issuecomment-628610729) should be running on 2021 relval samples from 11.0.0.
