### ISSUE TITLE
HCAL - Run3 preparation

### ISSUE THREAD

**Issue by mariadalfonso** [cms-patatrack/cmssw#539]
Here I keep track all the ongoing updates in the Run3 preparation, changes went in the 11_2_X release:

PR affecting CPU - to be checked/updated on GPU:

1. MC pulse shape 
https://github.com/cms-sw/cmssw/pull/31111
GPU should be transparent

2. noise correlation (for both data and MC)
https://github.com/cms-sw/cmssw/pull/31064
https://github.com/cms-sw/cmssw/pull/31513
https://github.com/cms-sw/cmssw/pull/32394
we should implement on GPU as well

GPU-code wish list:

A. what is in hcal:reconstruction are duplicated of various stuff in the cpu code
https://github.com/cms-patatrack/cmssw/blob/master/RecoLocalCalo/HcalRecProducers/src/KernelHelpers.h
understand if is possible to avoid the duplication

B. isolate method0, now buried inside RecoLocalCalo/HcalRecProducers/src/MahiGPU.cu ; code all the remaining TODO

**Comment by mariadalfonso** [comment]
- [ ] done in https://github.com/cms-patatrack/cmssw/pull/557

the fnnls is very similar between ECAL and HCAL: 
It differs only in the nan check 
https://github.com/cms-patatrack/cmssw/pull/523/files#diff-98f76d25429b5059efd61f6632594e42R116
and convergence parameters
https://github.com/cms-patatrack/cmssw/pull/523/files#diff-98f76d25429b5059efd61f6632594e42R116


- [ ] done in https://github.com/cms-patatrack/cmssw/pull/565

C. move the conditions in appropriate package (i.e.  CondFormats/HcalObjectsGPU)
for CPU they are in CondFormats/HcalObjects
for GPU they are in RecoLocalCalo/HcalRecAlgos

**Comment by mariadalfonso** [comment]
- [x] done in https://github.com/cms-patatrack/cmssw/pull/576

null pulse shape
https://github.com/cms-sw/cmssw/pull/32146/files#diff-aa9c764a605fbf5a6ab6036f537732475d05cd68ce3245ac85b4af63802772b1R258-R260

**Comment by fwyzard** [comment]
@mariadalfonso are these still open ?

> PR affecting CPU - to be checked/updated on GPU:
> 
> 1. MC pulse shape
> [cms-sw#31111](https://github.com/cms-sw/cmssw/pull/31111)
> GPU should be transparent
> 
>  2. noise correlation (for both data and MC)
>  [cms-sw#31064](https://github.com/cms-sw/cmssw/pull/31064)
>  [cms-sw#31513](https://github.com/cms-sw/cmssw/pull/31513)
>  we should implement on GPU as well

?

**Comment by fwyzard** [comment]
Moved to https://github.com/cms-sw/cmssw/issues/32413 .

**Comment by mariadalfonso** [comment]
I close this, we keep track on cms-sw
