### ISSUE TITLE
build and validate CMSSW_11_2_0_pre6_Patatrack

### ISSUE THREAD

**Issue by fwyzard** [cms-patatrack/cmssw#550]

**Comment by AdrianoDee** [comment]
## Validation summary
Reference release [CMSSW_11_2_0_pre6](https://github.com/cms-sw/cmssw/tree/CMSSW_11_2_0_pre6) at a01757690fd9
Development branch [cms-patatrack/master](https://github.com/cms-patatrack/cmssw/tree/master) at 54fb84978380

**Comment by AdrianoDee** [comment]
It seems to me this comes from a default naming mismatch between the `BeamSpotCUDA` in input [here](https://github.com/cms-patatrack/cmssw/blob/CMSSW_11_2_X_Patatrack/RecoLocalTracker/SiPixelRecHits/plugins/SiPixelRecHitCUDA.cc#L59) and the one produced [here](https://github.com/cms-sw/cmssw/blob/51f18ad645011763db0eccde292a389abde0b7af/RecoVertex/BeamSpotProducer/plugins/BeamSpotToCUDA.cc#L71) renamed with 51f18ad6450117

**Comment by AdrianoDee** [comment]
## Validation summary
Reference release [CMSSW_11_2_0_pre6](https://github.com/cms-sw/cmssw/tree/CMSSW_11_2_0_pre6) at 715db98a77e2
Development branch [cms-patatrack/master](https://github.com/cms-patatrack/cmssw/tree/master) at bbf9c1575ab6

**Comment by fwyzard** [comment]
Superseded by #554 .
