### ISSUE TITLE
CUDA cannot compile Eigen headers

### ISSUE THREAD

**Issue by rovere** [cms-patatrack/cmssw#6]
While starting to code an example of Eigen on GPU I stumbled upon the following compilation error:

```
In file included from /data/rovere/PatatrackHackaton2/RiemannFit/CMSSW_10_0_1/src/RecoPixelVertexing/PixelTrackFitting/test/testEigenGPU.cu:1:0:
/cvmfs/cms.cern.ch/slc7_amd64_gcc630/external/eigen/c7dc0a897676-cms/include/eigen3/Eigen/Core:59:34: fatal error: math_functions.hpp: No such file or directory
     #include <math_functions.hpp>
                                  ^
```

which apparently is due to the fact the CUDA include `math_functions.hpp` lives only in `CUDAROOTASEXTERNAL/include/crt` and is not present directly under `CUDAROOTASEXTERNAL/include`. Apparently a symlink should do the trick but I'm not able to test it under `/cvmfs`.

**Comment by fwyzard** [comment]
@rovere can you post a simple test ?

**Comment by rovere** [comment]
```c++
#include <Eigen/Core>
#include <Eigen/Eigenvalues>

int main (int argc, char * argv[]) {

  return 0;
}
```

**Comment by fwyzard** [comment]
Found plenty of discussion online - some claim CUDA should be fixed (symlink or `#include`), some that Eigen should be fixed (I think upstream it has been).

The easiest fix is to add `CUDA_BASE/include/crt` to the include path in cuda tool file, as it will not require rebuilding any externals.

Let me to that for the moment, and ask NVIDIA about the move to .../crt.

**Comment by rovere** [comment]
Yeah, those are most likely the same chat I read

**Comment by fwyzard** [comment]
Proposed solution for CMSSW 10.1.x: cms-sw/cmsdist#3724
Backport solution for CMSSW 10.0.x: cms-sw/cmsdist#3723

**Comment by fwyzard** [comment]
Workaround until those are integrated:
  - edit `$CMSSW_BASE/config/toolbox/slc7_amd64_gcc630/tools/selected/cuda.xml`
  - below the line
```xml
  <environment name="INCLUDE"   default="$CUDA_BASE/include"/>
```
add the line
```xml
  <environment name="INCLUDE"   default="$CUDA_BASE/include/crt"/>
```
  - run `scram setup cuda`

**Comment by fwyzard** [comment]
Fixed in CMSSW_10_1_0_pre1
